using System.Reflection;
using System.Runtime.CompilerServices;

// Information about this assembly is defined by the following attributes. 
// Change them to the values specific to your project.

[assembly: AssemblyTitle("Microsoft.Xna.Framework.Graphics")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// The form "{Major}.{Minor}.*" will automatically update the build and revision,
// and "{Major}.{Minor}.{Build}.*" will update just the revision.

[assembly: AssemblyVersion("4.0.0.0")]

// The following attributes are used to specify the signing key for the assembly, 
// if desired. See the Mono documentation for more information about signing.

[assembly: AssemblyDelaySign(true)]
[assembly: AssemblyKeyFile("../xna4.pub")]

/* Breaking MonoGame into independent assemblies is hard, so for now we forward the types to one monolithic assembly. */
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.AlphaTestEffect))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.Blend))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.BlendState))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.BufferUsage))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.ClearOptions))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.CompareFunction))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.CullMode))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.DepthFormat))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.DepthStencilState))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.DirectionalLight))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.DisplayMode))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.DisplayModeCollection))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.Effect))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.EffectParameter))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.EffectParameterClass))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.EffectParameterCollection))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.EffectParameterType))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.EffectPass))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.EffectPassCollection))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.FillMode))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.GraphicsAdapter))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.GraphicsDevice))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.GraphicsDeviceStatus))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.GraphicsProfile))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.GraphicsResource))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.IEffectFog))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.IEffectLights))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.IEffectMatrices))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.IndexBuffer))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.IndexElementSize))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.IVertexType))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.Model))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.ModelBone))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.ModelMesh))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.ModelMeshPart))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.PresentationParameters))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.RasterizerState))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.RenderTarget2D))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.RenderTargetBinding))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.RenderTargetUsage))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.SamplerState))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.SamplerStateCollection))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.SetDataOptions))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.SpriteBatch))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.SpriteEffects))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.SpriteFont))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.SpriteSortMode))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.StencilOperation))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.SurfaceFormat))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.Texture))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.Texture2D))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.TextureAddressMode))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.TextureCollection))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.TextureFilter))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexBuffer))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexDeclaration))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexElement))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexElementFormat))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexElementUsage))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexPositionColor))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexPositionNormalTexture))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.VertexPositionTexture))]
[assembly: TypeForwardedTo(typeof(Microsoft.Xna.Framework.Graphics.Viewport))]
